### PR TITLE
[DR-1630] Add prometheus scrape config for production

### PR DESCRIPTION
**Pull request by samanehsan**

### CODE REVIEW

**Comment by smark88** [comment]
We could test this in perf, alpha, stage well before prod but i dont think it will really break anything.

**Comment by nmalfroy** [comment]
This is great!  Sorry, getting to it late...would you mind terribly doing this on the fakeprod deployment too when you get a chance?

**Comment by samanehsan** [comment]
Sure!

**Comment by samanehsan** [comment]
@nmalfroy so I thought fake-prod followed the same pattern as the others, but it does not include any of the monitoring containers. @smark88 mentioned it has a broken prometheus and would probably be more effort to fix than it's worth.

**Comment by nmalfroy** [comment]
Fair enough.  Never mind then.  Thanks for looking!

**Pull request merged**
