### PR TITLE
[DR-3119] Make sure that dev can support testing protected data

### PR DESCRIPTION
**Pull request by nmalfroy**
Adds configuration to send logs to central logging for protected datasets

### CODE REVIEW

**Comment by samanehsan** [comment]
Do we also need this in the integration environments?

**Comment by nmalfroy** [comment]
It's a great question.  I debated but I don't think we do since none of the integration tests actually turn on secure monitoring for Azure (cause it can get expensive)

**Comment by samanehsan** [comment]
Got it! Thanks for clarifying!

**Review by samanehsan — APPROVED** [review]

**Review by snf2ye — APPROVED** [review]

**Review by s-rubenstein — APPROVED** [review]
The config LGTM. Would you mind updating the ticket with the note that we need it in dev as well? Right now it just says to do alpha, staging, and prod.

**Comment by nmalfroy** [comment]
Ah you got it!

**Pull request merged**
