### PR TITLE
helmfile/skaffold sync and added frontend config

### PR DESCRIPTION
**Pull request by smark88**
I noticed some drift in helmfile and skaffold so i took some time to update everyones yamls. Additionally I added frontend configs to all ingress controllers this adds http to https redirects and tls 1.2+ is required for certs. 

PLEASE REVIEW FOR YOUR ENVIRONMENT.

### CODE REVIEW

**Review by nmalfroy — APPROVED** [review]
mine looks good, thanks!

**Review by pshapiro4broad — APPROVED** [review]
lgtm

**Review by fboulnois — APPROVED** [review]
my changes lgtm

**Review by sfholden3 — APPROVED** [review]
Thank you - LGTM

**Pull request merged**
